version: '3.3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  web:
    build: ./../interview.io
    volumes:
      - ./../interview.io/app:/usr/src/app/app
      - ./../interview.io/src:/usr/src/app/src
      - ./../interview.io/web:/usr/src/app/web
      - ./../interview.io/templates:/usr/src/app/templates
    ports:
      - 5001:5001
    expose:
      - 5001
    depends_on:
      - mongo
